# -*- coding: utf-8 -*-
"""ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Santoshi1806/a2f0b4a748655f3773fab40f7fb90f55/task_4.ipynb
"""

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! npm install -g localtunnel@2.0.2

from google.colab import drive
drive.mount('/content/drive')

!streamlit run app.py & npx localtunnel --port 8501